version: "3.5"

services:
  shopapp:
    ports:
      - "80:80"
    build:
      context: .
      target: development
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    volumes:
      - ./:/app:cached
